from Tkinter import *
import py_compile
from subprocess import call
from PIL import ImageTk,Image
import os

root = Tk()
status = Label(root, text="APP CHECKING AGAINST APP DESCRIPTION",bd=3,relief=SUNKEN,anchor=W)
status.pack(side=BOTTOM,fill=X)

root.wm_title("MAP: App Checker")
img = ImageTk.PhotoImage(Image.open("test.jpg"))
#img=img.resize((250,250),Image.ANTIALIAS)
panel = Label(root, image = img)
panel.pack(side = "bottom", fill = "both", expand = "yes")



def topic():
	os.chdir("crawling")
	call("mkdir APPLY-TOPIC",shell=True)
	call("mkdir APPLY-TOPIC-NAME",shell=True)
	call("cp ENTERTAINMENT/ENTERTAINMENT-STEMMED/entertainmentstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp MEDICAL/MEDICAL-STEMMED/medicalstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp MUSIC/MUSIC-STEMMED/musicstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp NEWS/NEWS-STEMMED/newsstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp SHOPPING/SHOPPING-STEMMED/shoppingstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp SOCIAL/SOCIAL-STEMMED/socialstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp SPORTS/SPORTS-STEMMED/sportsstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp WEATHER/WEATHER-STEMMED/weatherstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp HEALTH/HEALTH-STEMMED/healthstemmed*.txt APPLY-TOPIC/",shell=True)
	call("cp LIFESTYLE/LIFESTYLE-STEMMED/lifestylestemmed*.txt APPLY-TOPIC/",shell=True)
    	call("cp ENTERTAINMENT/ENTERTAINMENT-TOPICS/t_entertainment*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp MEDICAL/MEDICAL-TOPICS/t_medical*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp MUSIC/MUSIC-TOPICS/t_music*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp NEWS/NEWS-TOPICS/t_news*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp SHOPPING/SHOPPING-TOPICS/t_shopping*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp SOCIAL/SOCIAL-TOPICS/t_social*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp SPORTS/SPORTS-TOPICS/t_sports*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp WEATHER/WEATHER-TOPICS/t_weather*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp HEALTH/HEALTH-TOPICS/t_health*.txt APPLY-TOPIC-NAME/",shell=True)
	call("cp LIFESTYLE/LIFESTYLE-TOPICS/t_lifestyle*.txt APPLY-TOPIC-NAME/",shell=True)
	os.chdir("../")
def topic1():
	os.chdir("lda_and_topic_create/")
	call("python topics.py",shell=True)
	os.chdir("../")
def cluster():
	os.chdir("lda_and_topic_create/")
	call("python lda1.py",shell=True)
	os.chdir("../")
def show1():
	os.chdir("lda_and_topic_create/")
	call("gedit info.txt",shell=True)
	os.chdir("../")
def show2():
	os.chdir("lda_and_topic_create/")
	call("gedit info1.txt",shell=True)
	os.chdir("../")

def doCrawling1():
	call("mkdir -p crawling/ENTERTAINMENT",shell=True)
	call("mv entertainmentcrawl.py crawling/ENTERTAINMENT",shell=True)	
	os.chdir("crawling")	
	os.chdir("ENTERTAINMENT")
	call("python entertainmentcrawl.py",shell=True)
	call("mkdir ENTERTAINMENT-DESC.",shell=True)
	call("mkdir ENTERTAINMENT-TOPICS",shell=True)
	call("mkdir ENTERTAINMENT-FILTER",shell=True)
	call("mkdir ENTERTAINMENT-STEMMED",shell=True)
	call("mv t_entertainment*.txt ENTERTAINMENT-TOPICS/",shell=True)
	call("mv entertainment*.txt ENTERTAINMENT-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")
def doCrawling2():
	call("mkdir -p crawling/MEDICAL",shell=True)
	call("mv medicalcrawl.py crawling/MEDICAL",shell=True)
	os.chdir("crawling")
	os.chdir("MEDICAL")
	call("python medicalcrawl.py",shell=True)
	call("mkdir MEDICAL-DESC.",shell=True)
	#call("mkdir -p crawling/MEDICAL",shell=True)
	call("mkdir MEDICAL-TOPICS",shell=True)
	call("mkdir MEDICAL-FILTER",shell=True)
	call("mkdir MEDICAL-STEMMED",shell=True)
	call("mv t_medical*.txt MEDICAL-TOPICS/",shell=True)
	call("mv medical*.txt MEDICAL-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling3():
	call("mkdir -p crawling/MUSIC",shell=True)
	call("mv musiccrawl.py crawling/MUSIC",shell=True)
	os.chdir("crawling")	
	os.chdir("MUSIC")
	call("python musiccrawl.py",shell=True)
	call("mkdir MUSIC-DESC.",shell=True)
	call("mkdir MUSIC-TOPICS",shell=True)
	call("mkdir MUSIC-FILTER",shell=True)
	call("mkdir MUSIC-STEMMED",shell=True)
	call("mv t_music*.txt MUSIC-TOPICS/",shell=True)
	call("mv music*.txt MUSIC-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")
def doCrawling4():
	call("mkdir -p crawling/NEWS",shell=True)
	call("mv newscrawl.py crawling/NEWS",shell=True)
	os.chdir("crawling")	
	os.chdir("NEWS")
	call("python newscrawl.py",shell=True)
	call("mkdir NEWS-DESC.",shell=True)
	call("mkdir NEWS-TOPICS",shell=True)
	call("mkdir NEWS-FILTER",shell=True)
	call("mkdir NEWS-STEMMED",shell=True)
	call("mv t_news*.txt NEWS-TOPICS/",shell=True)
	call("mv news*.txt NEWS-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling5():
	call("mkdir -p crawling/SHOPPING",shell=True)
	call("mv shoppingcrawl.py crawling/SHOPPING",shell=True)
	os.chdir("crawling")	
	os.chdir("SHOPPING")
	call("python shoppingcrawl.py",shell=True)
	call("mkdir SHOPPING-DESC.",shell=True)
	call("mkdir SHOPPING-TOPICS",shell=True)
	call("mkdir SHOPPING-FILTER",shell=True)
	call("mkdir SHOPPING-STEMMED",shell=True)
	call("mv t_shopping*.txt SHOPPING-TOPICS/",shell=True)
	call("mv shopping*.txt SHOPPING-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling6():
	call("mkdir -p crawling/SOCIAL",shell=True)
	call("mv socialcrawl.py crawling/SOCIAL",shell=True)
	os.chdir("crawling")
	os.chdir("SOCIAL")
	call("python socialcrawl.py",shell=True)
	call("mkdir SOCIAL-DESC.",shell=True)
	call("mkdir SOCIAL-TOPICS",shell=True)
	call("mkdir SOCIAL-FILTER",shell=True)
	call("mkdir SOCIAL-STEMMED",shell=True)
	call("mv t_social*.txt SOCIAL-TOPICS/",shell=True)
	call("mv social*.txt SOCIAL-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling7():
	call("mkdir -p crawling/SPORTS",shell=True)
	call("mv sportscrawl.py crawling/SPORTS",shell=True)
	os.chdir("crawling")
	os.chdir("SPORTS")
	call("python sportscrawl.py",shell=True)
	call("mkdir SPORTS-DESC.",shell=True)
	call("mkdir SPORTS-TOPICS",shell=True)
	call("mkdir SPORTS-FILTER",shell=True)
	call("mkdir SPORTS-STEMMED",shell=True)
	call("mv t_sports*.txt SPORTS-TOPICS/",shell=True)
	call("mv sports*.txt SPORTS-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling8():
	call("mkdir -p crawling/WEATHER",shell=True)
	call("mv weathercrawl.py crawling/WEATHER",shell=True)
	os.chdir("crawling")
	os.chdir("WEATHER")
	call("python weathercrawl.py",shell=True)
	call("mkdir WEATHER-DESC.",shell=True)
	call("mkdir WEATHER-TOPICS",shell=True)
	call("mkdir WEATHER-FILTER",shell=True)
	call("mkdir WEATHER-STEMMED",shell=True)
	call("mv t_weather*.txt WEATHER-TOPICS/",shell=True)
	call("mv weather*.txt WEATHER-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling9():
	call("mkdir -p crawling/HEALTH",shell=True)
	call("mv healthcrawl.py crawling/HEALTH",shell=True)
	os.chdir("crawling")
	os.chdir("HEALTH")
	call("python healthcrawl.py",shell=True)
	call("mkdir HEALTH-DESC.",shell=True)
	call("mkdir HEALTH-TOPICS",shell=True)
	call("mkdir HEALTH-FILTER",shell=True)
	call("mkdir HEALTH-STEMMED",shell=True)
	call("mv t_health*.txt HEALTH-TOPICS/",shell=True)
	call("mv health*.txt HEALTH-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def doCrawling10():
	call("mkdir -p crawling/LIFESTYLE",shell=True)
	call("mv lifestylecrawl.py crawling/LIFESTYLE",shell=True)
	os.chdir("crawling")
	os.chdir("LIFESTYLE")
	call("python lifestylecrawl.py",shell=True)
	call("mkdir LIFESTYLE-DESC.",shell=True)
	call("mkdir LIFESTYLE-TOPICS",shell=True)
	call("mkdir LIFESTYLE-FILTER",shell=True)
	call("mkdir LIFESTYLE-STEMMED",shell=True)
	call("mv t_lifestyle*.txt LIFESTYLE-TOPICS/",shell=True)
	call("mv lifestyle*.txt LIFESTYLE-DESC./",shell=True)
	os.chdir("../")
	os.chdir("../")

def dofilter1():
	os.chdir("stem_and_filter")
	call("cp filter-stem-ent.py ../crawling/ENTERTAINMENT/ENTERTAINMENT-DESC.",shell=True)
	os.chdir("../crawling/ENTERTAINMENT/ENTERTAINMENT-DESC./")
	call("python filter-stem-ent.py",shell=True)
	call("mv entertainmentfiltered*.txt ../ENTERTAINMENT-FILTER",shell=True)
	call("mv entertainmentstemmed*.txt ../ENTERTAINMENT-STEMMED",shell=True)
	call("mv filter-stem-ent.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter2():
	os.chdir("stem_and_filter")
	call("cp filter-stem-med.py ../crawling/MEDICAL/MEDICAL-DESC.",shell=True)
	os.chdir("../crawling/MEDICAL/MEDICAL-DESC./")
	call("python filter-stem-med.py",shell=True)
	call("mv medicalfiltered*.txt ../MEDICAL-FILTER",shell=True)
	call("mv medicalstemmed*.txt ../MEDICAL-STEMMED",shell=True)
	call("mv filter-stem-med.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter3():
	os.chdir("stem_and_filter")
	call("cp filter-stem-mus.py ../crawling/MUSIC/MUSIC-DESC.",shell=True)
	os.chdir("../crawling/MUSIC/MUSIC-DESC./")
	call("python filter-stem-mus.py",shell=True)
	call("mv musicfiltered*.txt ../MUSIC-FILTER",shell=True)
	call("mv musicstemmed*.txt ../MUSIC-STEMMED",shell=True)
	call("mv filter-stem-mus.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter4():
	os.chdir("stem_and_filter")
	call("cp filter-stem-new.py ../crawling/NEWS/NEWS-DESC.",shell=True)
	os.chdir("../crawling/NEWS/NEWS-DESC./")
	call("python filter-stem-new.py",shell=True)
	call("mv newsfiltered*.txt ../NEWS-FILTER",shell=True)
	call("mv newsstemmed*.txt ../NEWS-STEMMED",shell=True)
	call("mv filter-stem-new.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter5():
	os.chdir("stem_and_filter")
	call("cp filter-stem-sho.py ../crawling/SHOPPING/SHOPPING-DESC.",shell=True)
	os.chdir("../crawling/SHOPPING/SHOPPING-DESC./")
	call("python filter-stem-sho.py",shell=True)
	call("mv shoppingfiltered*.txt ../SHOPPING-FILTER",shell=True)
	call("mv shoppingstemmed*.txt ../SHOPPING-STEMMED",shell=True)
	call("mv filter-stem-sho.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter6():
	os.chdir("stem_and_filter")
	call("cp filter-stem-soc.py ../crawling/SOCIAL/SOCIAL-DESC.",shell=True)
	os.chdir("../crawling/SOCIAL/SOCIAL-DESC./")
	call("python filter-stem-soc.py",shell=True)
	call("mv socialfiltered*.txt ../SOCIAL-FILTER",shell=True)
	call("mv socialstemmed*.txt ../SOCIAL-STEMMED",shell=True)
	call("mv filter-stem-soc.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter7():
	os.chdir("stem_and_filter")
	call("cp filter-stem-spo.py ../crawling/SPORTS/SPORTS-DESC.",shell=True)
	os.chdir("../crawling/SPORTS/SPORTS-DESC./")
	call("python filter-stem-spo.py",shell=True)
	call("mv sportsfiltered*.txt ../SPORTS-FILTER",shell=True)
	call("mv sportsstemmed*.txt ../SPORTS-STEMMED",shell=True)
	call("mv filter-stem-spo.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter8():
	os.chdir("stem_and_filter")
	call("cp filter-stem-wea.py ../crawling/WEATHER/WEATHER-DESC.",shell=True)
	os.chdir("../crawling/WEATHER/WEATHER-DESC./")
	call("python filter-stem-wea.py",shell=True)
	call("mv weatherfiltered*.txt ../WEATHER-FILTER",shell=True)
	call("mv weatherstemmed*.txt ../WEATHER-STEMMED",shell=True)
	call("mv filter-stem-wea.py ../",shell=True)
	os.chdir("../../../")
	
def dofilter9():
	os.chdir("stem_and_filter")
	call("cp filter-stem-hea.py ../crawling/HEALTH/HEALTH-DESC.",shell=True)
	os.chdir("../crawling/HEALTH/HEALTH-DESC./")
	call("python filter-stem-hea.py",shell=True)
	call("mv healthfiltered*.txt ../HEALTH-FILTER",shell=True)
	call("mv healthstemmed*.txt ../HEALTH-STEMMED",shell=True)
	call("mv filter-stem-hea.py ../",shell=True)
	os.chdir("../../../")

def dofilter10():
	os.chdir("stem_and_filter")
	call("cp filter-stem-life.py ../crawling/LIFESTYLE/LIFESTYLE-DESC.",shell=True)
	os.chdir("../crawling/LIFESTYLE/LIFESTYLE-DESC./")
	call("python filter-stem-life.py",shell=True)
	call("mv lifestylefiltered*.txt ../LIFESTYLE-FILTER",shell=True)
	call("mv lifestylestemmed*.txt ../LIFESTYLE-STEMMED",shell=True)
	call("mv filter-stem-life.py ../",shell=True)
	os.chdir("../../../")

# Tkinter puts menus at the top by default
menu = Menu(root)
root.config(menu=menu)

subMenu = Menu(menu)
# Adds a drop down when "File" is clicked
menu.add_cascade(label="Data Crawler", menu=subMenu)
subMenu.add_command(label="Entertainment", command=doCrawling1)
subMenu.add_command(label="Medical", command=doCrawling2)
subMenu.add_command(label="Music", command=doCrawling3)
subMenu.add_command(label="News", command=doCrawling4)
subMenu.add_command(label="Shopping", command=doCrawling5)
subMenu.add_command(label="Social", command=doCrawling6)
subMenu.add_command(label="Sports", command=doCrawling7)
subMenu.add_command(label="Weather", command=doCrawling8)
subMenu.add_command(label="Health", command=doCrawling9)
subMenu.add_command(label="Lifestyle", command=doCrawling10)
subMenu.add_separator()
subMenu.add_command(label="Exit", command=root.quit)

editMenu = Menu(menu)
menu.add_cascade(label="Filter & Stemmer", menu=editMenu)
editMenu.add_command(label="Entertainment", command=dofilter1)
editMenu.add_command(label="Medical", command=dofilter2)
editMenu.add_command(label="Music", command=dofilter3)
editMenu.add_command(label="News", command=dofilter4)
editMenu.add_command(label="Shopping", command=dofilter5)
editMenu.add_command(label="Social", command=dofilter6)
editMenu.add_command(label="Sports", command=dofilter7)
editMenu.add_command(label="Weather", command=dofilter8)
editMenu.add_command(label="Health", command=dofilter9)
editMenu.add_command(label="Lifestyle", command=dofilter10)

editMenu = Menu(menu)
menu.add_cascade(label="Functions", menu=editMenu)
editMenu.add_command(label="Gathering Data", command=topic)
editMenu.add_command(label="Topic Creation", command=topic1)
editMenu.add_separator()
editMenu.add_command(label="LDA & Cluster", command=cluster)


editMenu = Menu(menu)
menu.add_cascade(label="Results", menu=editMenu)
editMenu.add_command(label="Topics Formed", command=show1)
editMenu.add_separator()
editMenu.add_command(label="Cluster Formed", command=show2)





root.mainloop()
